# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: newagent

steps:
- script: |
    # Download the chromedriver binary
    wget -q https://chromedriver.storage.googleapis.com/LATEST_RELEASE -O latest_release.txt
    wget -q https://chromedriver.storage.googleapis.com/$(cat latest_release.txt)/chromedriver_linux64.zip -P /tmp
    unzip /tmp/chromedriver_linux64.zip -d /tmp

    # Add chromedriver to PATH
    echo "export PATH=\$PATH:/tmp" >> ~/.bashrc
    source ~/.bashrc

  displayName: 'Install chromedriver'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

