trigger:
- master

pool: newagent

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y chromium-browser
  displayName: 'Install Chromium browser'
- script: |
    CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
    wget -qP /tmp/ "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
    unzip -qq -d /usr/local/bin/ "/tmp/chromedriver_linux64.zip"
    rm -f /tmp/chromedriver_linux64.zip
    sudo chmod +x /usr/local/bin/chromedriver
  displayName: 'Install ChromeDriver'
- script: |
    export DISPLAY=:99
    Xvfb :99 -screen 0 1024x768x16 &> /dev/null &
    sleep 3
    google-chrome-stable --disable-gpu --headless --remote-debugging-port=9222 http://localhost &
    sleep 3
  displayName: 'Start Xvfb and Chrome'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- script: |
    killall Xvfb
    killall google-chrome-stable
  displayName: 'Stop Xvfb and Chrome'
